### ISSUE TITLE
Unexpected results for keyword search

### ISSUE THREAD

**Issue by equivalentideas** [NSW-eTendering/NSW-eTendering-API#5]
Hi @andrewlorien-at-gruden 👋 

When I search 'WestConnex' on the website, I get 21 results: https://tenders.nsw.gov.au/?keyword=WestConnex&startRow=0&event=public.advancedsearch.keyword&refine=CN&resultsPerPage=90&orderBy=Relevance

When I search for the same term through the API, I only get 15: 

```ruby
per_page = 90
keyword = 'WestConnex'
contracts_search_url = "https://tenders.nsw.gov.au/?event=public.api.contract.search&type=cnEvent&invalidEventName=public.advancedsearch.checkTypeSearch&rftType=proposed%2Cpublished%2Cclosed%2Carchived&agencyStatus=-1&keyword=#{keyword}&resultsPerPage=#{per_page}"
contracts_search = JSON.parse(RestClient.get(contracts_search_url).body)
contracts_search["releases"].count
#=> 15
```

Do you know why I might find fewer contracts with this search?

**Comment by andrewlorien** [comment]
Sorry it's taken so long to get back to you...
That was a bug.  It was related to a pagination problem, the number of records returned by the search wasn't calculated properly so sometimes you didn't see all of them.  It will be fixed in the next release, due on 13/6/2018

**Comment by andrewlorien** [comment]
... and that release was deployed last month.
This api request
https://tenders.nsw.gov.au/?event=public.api.contract.search&&refine=CN&resultsPerPage=90&orderBy=Relevance&keyword=westconnex
now returns the same contracts as this advanced search:
https://tenders.nsw.gov.au/?event=public.advancedsearch.CNRedirect&invalidEventName=public.advancedsearch.checkTypeSearch&type=cnEvent&rftType=proposed%2Cpublished%2Cclosed%2Carchived&agencyUUID=&agencyStatus=-1&departmentUUID=&keyword=westconnex&publishFrom=&publishTo=&valueFrom=&valueTo=&supplierName=&supplierABN=&RFTID=&contractFrom=&contractTo=&submit=Search 

The API returns more because the advanced search does not return archived contracts ( those which closed more than 6 months ago).  This was a server capacity problem which does not affect the API.
